### ISSUE TITLE
How to speed ​​up the foolbox with FGSM?

### ISSUE THREAD

**Issue by wanghan0501** [bethgelab/foolbox#340] opened 2019-07-23 03:06 UTC
I use foolbox with FGSM to attack the pytorch model, however the runtime is so slow! I have already put data to *GPU*.  It costs about 7 mins on MNIST, however, when I run the code written by myself, it doesn't cost a long time.
```
device = 'cuda:0'
c_net = c_net.to(device)
c_net.eval()
fmodel = foolbox.models.PyTorchModel(
    c_net, bounds=(0, 1), num_classes=10, device=device)
attack = foolbox.attacks.FGSM(fmodel)
adversarial = attack(
            data_numpy, target_numpy, epsilons=1, max_epsilon=0.05)
```

my code:
```
x_adv = data.clone().detach().requires_grad_(True)
h_adv = c_net(x_adv)
cost = criterion(h_adv, target)
c_net.zero_grad()
if x_adv.grad is not None:
    x_adv.grad.data.fill_(0)
cost.backward()
x_adv.grad.sign_()
x_adv = x_adv + eps*x_adv.grad
x_adv = torch.clamp(x_adv, 0, 1)
```

I don't know the reason....

**Comment by wanghan0501** [comment] 2019-07-23 03:13
when I run my code on MNIST, it only costs about 7 sec... so, I need your help.

**Comment by jonasrauber** [comment] 2019-10-17 14:38
That certainly sounds wrong, but I cannot reproduce it using this code.
Ideally, please provide a full minimal example. One thing I noticed is that you call `attack` with something that looks like a batch, but at the same time you use `attacks.FGSM` instead of `batch_attacks.FGSM`. I would expect this to throw some shape errors.

For now, I am closing this but please reopen if you still encounter this behavior.

**Closed by jonasrauber** 2019-10-17 14:38 UTC
