### ISSUE TITLE
ValueError: attempt to get argmin of an empty sequence

### ISSUE THREAD

**Issue by ghofranGh2022** [bethgelab/foolbox#672] opened 2022-03-19 07:33 UTC
Hi,
i work with nicMSlesions approach, when i do the inference stap i find this error, 
Please, can you help me.
thanks.
![Capture22](https://user-images.githubusercontent.com/100536429/159112125-e40bb4a1-bad9-42a6-9416-b2549123867d.PNG)

**Comment by zimmerrol** [comment] 2022-03-19 15:26
Hi, please provide a minimal working example of the code that produces the error.

**Comment by ghofranGh2022** [comment] 2022-03-19 19:08
hi [zimmerrol], 
![Sans titre24](https://user-images.githubusercontent.com/100536429/159135081-f96a6ae6-dd69-4cea-9074-c57d18f25544.png)
thank you, this is my example code
![Sans titre23](https://user-images.githubusercontent.com/100536429/159135091-3d626166-7a40-4481-8404-142503fbac1d.png)

![Sans titre25](https://user-images.githubusercontent.com/100536429/159135077-d6bf5214-55c7-40d8-8f26-e9d769bc2334.png)

**Comment by ghofranGh2022** [comment] 2022-03-19 19:54
this is other example zimmerrol
![Sans titre26](https://user-images.githubusercontent.com/100536429/159136423-b07367d9-a9be-4b86-9c37-593331ed2246.png)

**Comment by ghofranGh2022** [comment] 2022-03-19 20:20
@zimmerrol

**Comment by zimmerrol** [comment] 2022-03-19 23:37
Unless you finally post the source code (and  ot a screenshot)for a [minimal working example](https://en.m.wikipedia.org/wiki/Minimal_reproducible_example), there is nothing I can/want to do.

**Comment by ghofranGh2022** [comment] 2022-03-20 07:47
@zimmerrol  ok i am sorry because this screen 
file preprocess.py :
import os
import shutil
import sys
import signal
import subprocess
import time
import platform
import nibabel as nib
import numpy as np
import SimpleITK as sitk
from medpy.filter.smoothing import anisotropic_diffusion as ans_dif


def get_mode(input_data):
    """
    Get the stastical mode
    """
    (_, idx, counts) = np.unique(input_data,
                                 return_index=True,
                                 return_counts=True)
    index = idx[np.argmax(counts)]
    mode = input_data[index]

    return mode

def parse_input_masks(current_folder, options):
    """
    identify input image masks parsing image name labels
    Check for input modalities. If lesiomask is not found, the mask
    is ignored

    """

    # if options['task'] == 'training':
    #     modalities = options['modalities'][:] + ['lesion']
    #     image_tags = options['image_tags'][:] + options['roi_tags'][:]
    # else:
    #     modalities = options['modalities'][:]
    #     image_tags = options['image_

    modalities = options['modalities'][:]
    image_tags = options['image_tags'][:]

    if options['debug']:
        print ("> DEBUG:", "number of input sequences to find:", len(modalities))

    scan = options['tmp_scan']
    print ("> PRE:", scan, "identifying input modalities")

    found_modalities = 0

    masks = [m for m in os.listdir(current_folder) if m.find('.nii') > 0]

    for t, m in zip(image_tags, modalities):

        # check first the input modalities
        # find tag

        found_mod = [mask.find(t) if mask.find(t) >= 0
                     else np.Inf for mask in masks]

        if found_mod[np.argmin(found_mod)] is not np.Inf:
            found_modalities += 1
            index = np.argmin(found_mod)
            # generate a new output image modality
            # check for extra dimensions
            input_path = os.path.join(current_folder, masks[index])
            input_sequence = nib.load(input_path)
            input_image = np.squeeze(input_sequence.get_data())
            output_sequence = nib.Nifti1Image(input_image,
                                              affine=input_sequence.affine)
            output_sequence.to_filename(
                os.path.join(options['tmp_folder'], m + '.nii.gz'))

            if options['debug']:
                print ("    --> ", masks[index], "as", m, "image")
            masks.remove(masks[index])

    # check that the minimum number of modalities are used
    if found_modalities < len(modalities):
        print ("> ERROR:", scan, "does not contain all valid input modalities")
        sys.stdout.flush()
        time.sleep(1)
        os.kill(os.getpid(), signal.SIGTERM)

    # check if lesion mask exists, and if not, save an empty mask
    # with same shape as T1-w

    t = options['roi_tags'][0]
    m = 'lesion'

    masks = [mask for mask in os.listdir(current_folder) if mask.find('.nii') > 0]
    found_mod = [mask.find(t) if mask.find(t) >= 0
                     else np.Inf for mask in masks]

    if found_mod[np.argmin(found_mod)] is not np.Inf:
        index = np.argmin(found_mod)
        # generate a new output image modality
        # check for extra dimensions
        input_path = os.path.join(current_folder, masks[index])
        input_sequence = nib.load(input_path)
        input_image = np.squeeze(input_sequence.get_data())
        output_sequence = nib.Nifti1Image(input_image,
                                          affine=input_sequence.affine)
        output_sequence.to_filename(
            os.path.join(options['tmp_folder'], m + '.nii.gz'))

        if options['debug']:
            print ("    --> ", masks[index], "as", m, "image")
            masks.remove(masks[index])
    else:
        ref_scan = nib.load(os.path.join(current_folder, 'tmp', 'T1.nii.gz'))
        input_image = np.zeros_like(ref_scan.get_data())
        output_sequence = nib.Nifti1Image(input_image,
                                          affine=ref_scan.affine)
        output_sequence.to_filename(
            os.path.join(options['tmp_folder'], m + '.nii.gz'))
        if options['debug']:
            print ("    -->  Empty mask as", m, "image")
            masks.remove(masks[index])

def register_masks(options):
    """
    - to doc
    - moving all images to the MPRAGE+192 space

    """

    scan = options['tmp_scan']
    # rigid registration
    os_host = platform.system()
    if os_host == 'Windows':
        reg_exe = 'reg_aladin.exe'
    elif os_host == 'Linux':
        reg_exe = 'reg_aladin'
    else:
        print ("> ERROR: The OS system", os_host, "is not currently supported.")

    reg_aladin_path = os.path.join(options['niftyreg_path'], reg_exe)

    for mod in options['modalities']:
        if mod == 'T1':
            continue

        try:
            print ("> PRE:", scan, "registering",  mod, " --> T1 space")
            subprocess.check_output([reg_aladin_path, '-ref',
                                     os.path.join(options['tmp_folder'], 'T1.nii.gz'),
                                     '-flo', os.path.join(options['tmp_folder'], mod + '.nii.gz'),
                                     '-aff', os.path.join(options['tmp_folder'], mod + '_transf.txt'),
                                     '-res', os.path.join(options['tmp_folder'], 'r' + mod + '.nii.gz')])
        except:
            print ("> ERROR:", scan, "registering masks on  ", mod, "quiting program.")
            time.sleep(1)
            os.kill(os.getpid(), signal.SIGTERM)

    # if training, the lesion mask is also registered through the T1 space.
    # Assuming that the refefence lesion space was FLAIR.
    if options['task'] == 'training':
        # rigid registration
        os_host = platform.system()
        if os_host == 'Windows':
            reg_exe = 'reg_resample.exe'
        elif os_host == 'Linux':
            reg_exe = 'reg_resample'
        else:
            print ("> ERROR: The OS system", os_host, "is not currently supported.")

        reg_resample_path = os.path.join(options['niftyreg_path'], reg_exe)

        try:
            print ("> PRE:", scan, "resampling the lesion mask --> T1 space")
            subprocess.check_output([reg_resample_path, '-ref',
                                     os.path.join(options['tmp_folder'], 'T1.nii.gz'),
                                     '-flo', os.path.join(options['tmp_folder'], 'lesion'),
                                     '-trans', os.path.join(options['tmp_folder'], 'FLAIR_transf.txt'),
                                     '-res', os.path.join(options['tmp_folder'], 'lesion.nii.gz'),
                                     '-inter', '0'])
        except:
            print ("> ERROR:", scan, "registering masks on  ", mod, "quiting program.")
            time.sleep(1)
            os.kill(os.getpid(), signal.SIGTERM)


def denoise_masks(options):
    """
    Denoise input masks to reduce noise.
    Using anisotropic Diffusion (Perona and Malik)

    """

    for mod in options['modalities']:

        current_image = mod + '.nii.gz' if mod == 'T1'\
                        else 'r' + mod + '.nii.gz'

        tmp_scan = nib.load(os.path.join(options['tmp_folder'],
                                         current_image))

        tmp_scan.get_data()[:] = ans_dif(tmp_scan.get_data(),
                                         niter=options['denoise_iter'])

        tmp_scan.to_filename(os.path.join(options['tmp_folder'],
                                          'd' + current_image))
        if options['debug']:
            print ("> DEBUG: Denoising ", current_image)


def skull_strip(options):
    """
    External skull stripping using ROBEX: Run Robex and save skull
    stripped masks
    input:
       - options: contains the path to input images
    output:
    - None
    """

    scan = options['tmp_scan']
    t1_im = os.path.join(options['tmp_folder'], 'dT1.nii.gz')
    t1_st_im = os.path.join(options['tmp_folder'], 'T1_brain.nii.gz')

    try:
        print ("> PRE:", scan, "skull_stripping the T1 modality")
        subprocess.check_output([options['robex_path'],
                                 t1_im,
                                 t1_st_im])
    except:
        print ("> ERROR:", scan, "registering masks, quiting program.")
        time.sleep(1)
        os.kill(os.getpid(), signal.SIGTERM)

    brainmask = nib.load(t1_st_im).get_data() > 1
    for mod in options['modalities']:

        if mod == 'T1':
            continue

        # apply the same mask to the rest of modalities to reduce
        # computational time

        print ('> PRE: ', scan, 'Applying skull mask to ', mod, 'image')
        current_mask = os.path.join(options['tmp_folder'],
                                    'dr' + mod + '.nii.gz')
        current_st_mask = os.path.join(options['tmp_folder'],
                                       mod + '_brain.nii.gz')

        mask = nib.load(current_mask)
        mask_nii = mask.get_data()
        mask_nii[brainmask == 0] = 0
        mask.get_data()[:] = mask_nii
        mask.to_filename(current_st_mask)


def preprocess_scan(current_folder, options):
    """
    Preprocess scan taking into account user options
    - input:
      current_folder = path to the current image
      options: options

    """
    preprocess_time = time.time()

    scan = options['tmp_scan']
    try:
        # os.rmdir(os.path.join(current_folder,  'tmp'))
        os.mkdir(options['tmp_folder'])
    except:
        if os.path.exists(options['tmp_folder']) is False:
            print("> ERROR:",  scan, "I can not create tmp folder for", current_folder, "Quiting program.")

        else:
            pass

    # --------------------------------------------------
    # find modalities and move everything to a tmp folder
    # --------------------------------------------------
    id_time = time.time()
    parse_input_masks(current_folder, options)
    #parse_input_masks('/content/gdrive/MyDrive/nicMSlesions1/train_folder/CHB_train_Case01_lesion.nii.gz', options)
    print ("> INFO:", scan, "elapsed time: ", round(time.time() - id_time), "sec")

    # --------------------------------------------------
    # register modalities
    # --------------------------------------------------
    if options['register_modalities'] is True:
        reg_time = time.time()
        register_masks(options)
        print ("> INFO:", scan, "elapsed time: ", round(time.time() - reg_time), "sec")
    else:
        try:
            for mod in options['modalities']:
                if mod == 'T1':
                    continue
                out_scan = mod + '.nii.gz' if mod == 'T1' else 'r' + mod + '.nii.gz'
                shutil.copy2(os.path.join(options['tmp_folder'],
                                         mod + '.nii.gz'),
                             os.path.join(options['tmp_folder'],
                                         out_scan))
        except:
            print ("> ERROR: registration ", scan, "I can not rename input modalities as tmp files. Quiting program.")

            time.sleep(1)
            os.kill(os.getpid(), signal.SIGTERM)

    # --------------------------------------------------
    # noise filtering
    # --------------------------------------------------
    if options['denoise'] is True:
        denoise_time = time.time()
        denoise_masks(options)
        print ("> INFO: denoising", scan, "elapsed time: ", round(time.time() - denoise_time), "sec")
    else:
        try:
            for mod in options['modalities']:
                input_scan = mod + '.nii.gz' if mod == 'T1' else 'r' + mod + '.nii.gz'
                shutil.copy(os.path.join(options['tmp_folder'],
                                         input_scan),
                            os.path.join(options['tmp_folder'],
                                         'd' + input_scan))
        except:
            print ("> ERROR denoising:", scan, "I can not rename input modalities as tmp files. Quiting program.")
            time.sleep(1)
            os.kill(os.getpid(), signal.SIGTERM)

    # --------------------------------------------------
    # skull strip
    # --------------------------------------------------

    if options['skull_stripping'] is True:
        sk_time = time.time()
        skull_strip(options)
        print ("> INFO:", scan, "elapsed time: ", round(time.time() - sk_time), "sec")
    else:
        try:
            for mod in options['modalities']:
                input_scan = 'd' + mod + '.nii.gz' if mod == 'T1' else 'dr' + mod + '.nii.gz'
                shutil.copy(os.path.join(options['tmp_folder'],
                                         input_scan),
                            os.path.join(options['tmp_folder'],
                                         mod + '_brain.nii.gz'))
        except:
            print ("> ERROR: Skull-stripping", scan, "I can not rename input modalities as tmp files. Quiting program.")
            time.sleep(1)
            os.kill(os.getpid(), signal.SIGTERM)

    if options['skull_stripping'] is True and options['register_modalities'] is True:
        print ("> INFO:", scan, "total preprocessing time: ", round(time.time() - preprocess_time))

**Comment by ghofranGh2022** [comment] 2022-03-20 07:49
@zimmerrol  also the infer-code is:
# ---------------------------------------------------------------------------------------
#   MS lesion segmentation pipeline
# ---------------------------------
#   - incorporates:
#         - MRI identification
#         - registration
#         - skull stripping
#         - MS lesion segmentation using the CNN Valverde et al (NI2017)
#
#  Sergi Valverde 2017
#  svalverde@eia.udg.edu
# ---------------------------------------------------------------------------------------

import os
import argparse
import sys
import platform
import time
import configparser
from utils.load_options import load_options, print_options
from utils.preprocess import preprocess_scan
from utils.postprocess import invert_registration
from shutil import copyfile

os.system('cls' if platform.system() == 'Windows' else 'clear')
print ("##################################################")
print ("# MS WM lesion segmentation                      #")
print ("#                                                #")
print ("# -------------------------------                #")
print ("# (c) Sergi Valverde 2019                        #")
print ("# Neuroimage Computing Group                     #")
print ("# -------------------------------                #")
print ("##################################################\n")

# link related libraries
CURRENT_PATH = os.path.split(os.path.realpath(__file__))[0]
sys.path.append(os.path.join(CURRENT_PATH, 'libs'))

# load options from input
parser = argparse.ArgumentParser()
parser.add_argument('--docker',
                    dest='docker',
                    action='store_true')
parser.set_defaults(docker=False)
args = parser.parse_args()
container = args.docker

# --------------------------------------------------
# load default options and update them with user information
# from utils.load_options import *
# --------------------------------------------------
default_config = configparser.SafeConfigParser()
default_config.read(os.path.join(CURRENT_PATH, 'config', 'default.cfg'))
user_config = configparser.RawConfigParser()
user_config.read(os.path.join(CURRENT_PATH, 'config', 'configuration.cfg'))

# read user's configuration file
options = load_options(default_config, user_config)

if options['debug']:
    print_options(options)

# tensorflow backend
device = str(options['gpu_number'])
print ("DEBUG: ", device)
os.environ['KERAS_BACKEND'] = 'tensorflow'
os.environ["CUDA_VISIBLE_DEVICES"] = device

# set paths taking into account the host OS
host_os = platform.system()
if host_os == 'Linux':
    options['niftyreg_path'] = CURRENT_PATH + '/libs/linux/niftyreg'
    options['robex_path'] = CURRENT_PATH + '/libs/linux/ROBEX/runROBEX.sh'
    options['test_slices'] = 256
elif host_os == 'Windows':
    options['niftyreg_path'] = os.path.normpath(
        os.path.join(CURRENT_PATH, 'libs', 'win', 'niftyreg'))
    options['robex_path'] = os.path.normpath(
        os.path.join(CURRENT_PATH, 'libs', 'win', 'ROBEX', 'runROBEX.bat'))
    options['test_slices'] = 256
else:
    "> ERROR: The OS system", host_os, "is not currently supported"

from CNN.base import test_cascaded_model
from CNN.build_model import cascade_model

# --------------------------------------------------
# net configuration
# take into account if the pretrained models have to be used
# all images share the same network model
# --------------------------------------------------
options['full_train'] = True
options['load_weights'] = True
options['weight_paths'] = os.path.join(CURRENT_PATH, 'nets')
options['net_verbose'] = 0

model = cascade_model(options)

# --------------------------------------------------
# process each of the scans
# - image identification
# - image registration
# - skull-stripping
# - WM segmentation
# --------------------------------------------------

if container:
    options['test_folder'] = os.path.normpath('/data' + options['test_folder'])
    #options['test_folder'] = os.path.normpath('/content/gdrive/MyDrive/nicMSlesions/database/inference_folder' + options['test_folder'])
else:
    options['test_folder'] = os.path.normpath(options['test_folder'])

# set task to train
options['task'] = 'inference'

# list scans
scan_list = os.listdir(options['test_folder'])
scan_list.sort()

for scan in scan_list:

    total_time = time.time()
    options['tmp_scan'] = scan
    # --------------------------------------------------
    # move things to a tmp folder before starting
    # --------------------------------------------------

    current_folder = os.path.join(options['test_folder'], scan)
    options['tmp_folder'] = os.path.normpath(
        os.path.join(current_folder,  'tmp'))

    # --------------------------------------------------
    # preprocess scans
    # --------------------------------------------------
    preprocess_scan(current_folder, options)

    # --------------------------------------------------
    # WM MS lesion inference
    # --------------------------------------------------
    seg_time = time.time()

    "> CNN:", scan, "running WM lesion segmentation"
    sys.stdout.flush()
    options['test_scan'] = scan

    test_x_data = {scan: {m: os.path.join(options['tmp_folder'], n)
                          for m, n in zip(options['modalities'],
                                          options['x_names'])}}

    out_seg = test_cascaded_model(model, test_x_data, options)

    print ("> INFO:", scan, "CNN Segmentation time: ",\
        round(time.time() - seg_time), "sec")

    # If input images have been registered before segmentation -> T1w space,
    # then resample the segmentation  back to the original space
    if options['register_modalities']:
        print ("> INFO:", scan, "Inverting lesion segmentation masks")
        invert_registration(current_folder, options)

    print ("> INFO:", scan, "total pipeline time: ",\
        round(time.time() - total_time), "sec")

    # remove tmps if not set
    if options['save_tmp'] is False:
        try:
            copyfile(os.path.join(current_folder,
                                  options['experiment'],
                                  options['experiment'] +
                                  '_out_CNN.nii.gz'),
                     os.path.join(current_folder,
                                  'out_seg_' +
                                  options['experiment'] +
                                  '.nii.gz'))
            os.rmdir(options['tmp_folder'])
            os.rmdir(os.path.join(options['current_folder'],
                                  options['experiment']))
        except:
            pass

print ("> INFO: All processes have been finished. Have a good day!")

**Comment by ghofranGh2022** [comment] 2022-03-20 07:50
@zimmerrol  i have error in preprocess.py

**Comment by zimmerrol** [comment] 2022-03-20 15:28
Sorry, but this is *not* a **minimal** working example. Please reduce your code to the minimum, as I otherwise won't have time to look at the root of your problems and will close the issue.

**Comment by ghofranGh2022** [comment] 2022-03-20 21:09
@zimmerrol  ok i will do a minimal example , i am sorry

**Comment by zimmerrol** [comment] 2022-03-29 19:17
Closing due to inactivity.

**Closed** 2022-03-29 19:17 UTC
Labels: question

**Comment by ghofranGh2022** [comment] 2022-03-29 20:59
Hi @zimmerrol  
I apologize, I can't make an example that sums up my problem,
my main problem is that the nicMSlesions approach of Sergi Valverde sur Google Colab is not working with me till now!!!!! I used data as input but no result is displayed,!!!!!!!!!!!!!!! I don't know what I should do!!!!!!!!!

**Comment by jangop** [comment] 2022-03-30 05:11
Does not seem to be directly related to foolbox. I suggest seeking help elsewhere, e.g. with a colleague.
