### ISSUE TITLE
Where is Saliency Map Attack method in foolbox version 3 ???

### ISSUE THREAD

**Issue by TheBloodthirster** [bethgelab/foolbox#646] opened 2021-09-22 12:04 UTC
I saw the issue https://github.com/bethgelab/foolbox/issues/252

which is say JSMA in foolbox in named Saliency Map Attack?

But I can't anything about key word Saliency in document?

And I find this method is defined in version 2.4.0. 

Could anyone tell what's gong on ? How to use JSMA in version 3?

**Comment by jangop** [comment] 2022-01-25 13:03
Duplicate of #645

**Closed** 2022-01-27 13:03 UTC
