### ISSUE TITLE
numba issue with LpBrendelBethgeAttack 

### ISSUE THREAD

**Issue by FlorianMerkle** [bethgelab/foolbox#545] opened 2020-05-19 10:32 UTC
Hi,
I am trying to get the Brendel Bethge Attack to work with my TF model but running into some troubles. This is how I invoke the attack (a working minimal example including my model definition can be found here: https://gist.github.com/FlorianMerkle/7266aa89c8547933c1ad6324c2a88418) 

```
attack = fb.attacks.L0BrendelBethgeAttack()
adversarials = attack(
    fmodel,
    x,
    y,
    epsilons=None
)
```

This is the end of the error stack:
```
Failed in nopython mode pipeline (step: nopython frontend)
Failed in nopython mode pipeline (step: nopython frontend)
Failed in nopython mode pipeline (step: nopython frontend)
Failed in nopython mode pipeline (step: nopython frontend)
Failed in nopython mode pipeline (step: nopython frontend)
Type of variable 'a_j.8' cannot be determined, operation: phi(incoming_values=[Var(a_j.9, brendel_bethge.py:1127), Undefined], incoming_blocks=[1518, 230]), location: /Users/florianmerkle/dev/foolbox/foolbox/attacks/brendel_bethge.py (1127)

File "../../foolbox/foolbox/attacks/brendel_bethge.py", line 1127:
    def _line_search_wolfe(  # noqa: C901
        <source elided>
                        (k == 0)
                        or (a_j is None)
                        ^

[1] During: resolving callee type: BoundFunction((<class 'numba.core.types.misc.ClassInstanceType'>, '_line_search_wolfe') for instance.jitclass.BFGSB#636b774d0<>)
[2] During: typing of call at /Users/florianmerkle/dev/foolbox/foolbox/attacks/brendel_bethge.py (844)

[3] During: resolving callee type: BoundFunction((<class 'numba.core.types.misc.ClassInstanceType'>, '_line_search_wolfe') for instance.jitclass.BFGSB#636b774d0<>)
[4] During: typing of call at /Users/florianmerkle/dev/foolbox/foolbox/attacks/brendel_bethge.py (844)

[5] During: resolving callee type: BoundFunction((<class 'numba.core.types.misc.ClassInstanceType'>, '_line_search_wolfe') for instance.jitclass.BFGSB#636b774d0<>)
[6] During: typing of call at /Users/florianmerkle/dev/foolbox/foolbox/attacks/brendel_bethge.py (844)
```

I do not fully understand how numba works but I guess at compile time it is checking for the possible conditions, and indeed a_j (and cchk for that matter) might be undefined. 

Versions are:
TF 2.1
numba 0.49.1

I already fixed the typo as per PR #544

**Comment by chawins** [comment] 2020-05-29 07:47
Having the same issue with PyTorch model and LinfBrendelBethgeAttack.
pytorch 1.4 and numba 0.49.1

**Comment by jonasrauber** [comment] 2020-05-29 09:39
@wielandbrendel

**Comment by wielandbrendel** [comment] 2020-06-18 20:51
@chawins @FlorianMerkle Sorry for the delay. I couldn't reproduce the exact issue you had, but another one when updating numba to the latest version. Could you check whether this also solves your problem?

**Comment by chawins** [comment] 2020-06-19 07:10
@wielandbrendel I installed foolbox directly from github master branch. The problem still persists with numba 0.49. Below are the full error trace I got:

Traceback (most recent call last):
  File "test_cifar.py", line 190, in <module>
    main()
  File "test_cifar.py", line 167, in main
    y_test[:num_test_samples].to(device), x_init.to(device), config)
  File "test_cifar.py", line 36, in bb_attack
    starting_points=x_init[begin:end])[1]
  File "/home/chawin/miniconda3/lib/python3.7/site-packages/foolbox/attacks/base.py", line 410, in __call__
    xp = self.run(model, x, criterion, early_stop=early_stop, **kwargs)
  File "/home/chawin/miniconda3/lib/python3.7/site-packages/foolbox/attacks/brendel_bethge.py", line 555, in run
    _x0, _x, _b, bounds[0], bounds[1], _c, r
  File "/home/chawin/miniconda3/lib/python3.7/site-packages/numba/experimental/jitclass/boxing.py", line 60, in wrapper
    return method(*args, **kwargs)
  File "/home/chawin/miniconda3/lib/python3.7/site-packages/numba/core/dispatcher.py", line 401, in _compile_for_args
    error_rewrite(e, 'typing')
  File "/home/chawin/miniconda3/lib/python3.7/site-packages/numba/core/dispatcher.py", line 344, in error_rewrite
    reraise(type(e), e, None)
  File "/home/chawin/miniconda3/lib/python3.7/site-packages/numba/core/utils.py", line 80, in reraise
    raise value.with_traceback(tb)
numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Failed in nopython mode pipeline (step: nopython frontend)
Failed in nopython mode pipeline (step: nopython frontend)
Failed in nopython mode pipeline (step: nopython frontend)
Failed in nopython mode pipeline (step: nopython frontend)
Type of variable 'a_j.8' cannot be determined, operation: phi(incoming_values=[Var(a_j.9, brendel_bethge.py:1121), Undefined], incoming_blocks=[1518, 230]), location: /home/chawin/miniconda3/lib/python3.7/site-packages/foolbox/attacks/brendel_bethge.py (1121)

File "../../../../home/chawin/miniconda3/lib/python3.7/site-packages/foolbox/attacks/brendel_bethge.py", line 1121:
    def _line_search_wolfe(  # noqa: C901
        <source elided>
                        (k == 0)
                        or (a_j is None)
                        ^

[1] During: resolving callee type: BoundFunction((<class 'numba.core.types.misc.ClassInstanceType'>, '_line_search_wolfe') for instance.jitclass.BFGSB#7f1333ae14d0<>)
[2] During: typing of call at /home/chawin/miniconda3/lib/python3.7/site-packages/foolbox/attacks/brendel_bethge.py (844)

[3] During: resolving callee type: BoundFunction((<class 'numba.core.types.misc.ClassInstanceType'>, '_line_search_wolfe') for instance.jitclass.BFGSB#7f1333ae14d0<>)
[4] During: typing of call at /home/chawin/miniconda3/lib/python3.7/site-packages/foolbox/attacks/brendel_bethge.py (844)

[5] During: resolving callee type: BoundFunction((<class 'numba.core.types.misc.ClassInstanceType'>, '_line_search_wolfe') for instance.jitclass.BFGSB#7f1333ae14d0<>)
[6] During: typing of call at /home/chawin/miniconda3/lib/python3.7/site-packages/foolbox/attacks/brendel_bethge.py (844)


File "../../../../home/chawin/miniconda3/lib/python3.7/site-packages/foolbox/attacks/brendel_bethge.py", line 844:
    def solve(
        <source elided>
            ) = self._line_search_wolfe(
                fun_and_jac, qk, pk, _gfk, old_fval, old_old_fval, l, u, args
                ^

[1] During: resolving callee type: BoundFunction((<class 'numba.core.types.misc.ClassInstanceType'>, 'solve') for instance.jitclass.BFGSB#7f1333ae14d0<>)
[2] During: typing of call at /home/chawin/miniconda3/lib/python3.7/site-packages/foolbox/attacks/brendel_bethge.py (282)

[3] During: resolving callee type: BoundFunction((<class 'numba.core.types.misc.ClassInstanceType'>, 'solve') for instance.jitclass.BFGSB#7f1333ae14d0<>)
[4] During: typing of call at /home/chawin/miniconda3/lib/python3.7/site-packages/foolbox/attacks/brendel_bethge.py (282)


File "../../../../home/chawin/miniconda3/lib/python3.7/site-packages/foolbox/attacks/brendel_bethge.py", line 282:
    def optimize_boundary_s_t_trustregion(self, x0, x, b, min_, max_, c, r):
        <source elided>
        qk = self.bfgsb.solve(
            self.optimize_boundary_s_t_trustregion_fun_and_jac, params0, bounds, args
            ^

[1] During: resolving callee type: BoundFunction((<class 'numba.core.types.misc.ClassInstanceType'>, 'optimize_boundary_s_t_trustregion') for instance.jitclass.LinfOptimizer#7f1332d98590<bfgsb:instance.jitclass.BFGSB#7f1333ae14d0<>>)
[2] During: typing of call at /home/chawin/miniconda3/lib/python3.7/site-packages/foolbox/attacks/brendel_bethge.py (68)

[3] During: resolving callee type: BoundFunction((<class 'numba.core.types.misc.ClassInstanceType'>, 'optimize_boundary_s_t_trustregion') for instance.jitclass.LinfOptimizer#7f1332d98590<bfgsb:instance.jitclass.BFGSB#7f1333ae14d0<>>)
[4] During: typing of call at /home/chawin/miniconda3/lib/python3.7/site-packages/foolbox/attacks/brendel_bethge.py (73)

[5] During: resolving callee type: BoundFunction((<class 'numba.core.types.misc.ClassInstanceType'>, 'optimize_boundary_s_t_trustregion') for instance.jitclass.LinfOptimizer#7f1332d98590<bfgsb:instance.jitclass.BFGSB#7f1333ae14d0<>>)
[6] During: typing of call at /home/chawin/miniconda3/lib/python3.7/site-packages/foolbox/attacks/brendel_bethge.py (96)

[7] During: resolving callee type: BoundFunction((<class 'numba.core.types.misc.ClassInstanceType'>, 'optimize_boundary_s_t_trustregion') for instance.jitclass.LinfOptimizer#7f1332d98590<bfgsb:instance.jitclass.BFGSB#7f1333ae14d0<>>)
[8] During: typing of call at /home/chawin/miniconda3/lib/python3.7/site-packages/foolbox/attacks/brendel_bethge.py (68)


File "../../../../home/chawin/miniconda3/lib/python3.7/site-packages/foolbox/attacks/brendel_bethge.py", line 68:
    def solve(self, x0, x, b, min_, max_, c, r):
        <source elided>
                _delta = self.optimize_boundary_s_t_trustregion(
                    x0, x, b, min_, max_, c, r
                    ^

[1] During: resolving callee type: BoundFunction((<class 'numba.core.types.misc.ClassInstanceType'>, 'solve') for instance.jitclass.LinfOptimizer#7f1332d98590<bfgsb:instance.jitclass.BFGSB#7f1333ae14d0<>>)
[2] During: typing of call at <string> (3)

[3] During: resolving callee type: BoundFunction((<class 'numba.core.types.misc.ClassInstanceType'>, 'solve') for instance.jitclass.LinfOptimizer#7f1332d98590<bfgsb:instance.jitclass.BFGSB#7f1333ae14d0<>>)
[4] During: typing of call at <string> (3)


File "<string>", line 3:
<source missing, REPL/exec in use?>

**Comment by wielandbrendel** [comment] 2020-06-19 07:28
I can reproduce the error with numba version 0.49.0 and 0.49.1 but the versions before and after work fine. So I guess this error is caused by a digression in numba and I'll add a warning.

**Closed** 2020-06-19 09:15 UTC
