### ISSUE TITLE
BrendelBethgeAttack arguments

### ISSUE THREAD

**Issue by mcguires5** [bethgelab/foolbox#539] opened 2020-04-16 06:38 UTC
```
attack = foolbox.attacks.L2BrendelBethgeAttack(fmodel, foolbox.criteria.Misclassification(y_test))
attack(i, label)
```

returns the error
  File "C:/Users/Sean/PycharmProjects/BroadSpectrumDefense/attacks_ART.py", line 390, in generate_attack_Foolbox
    x_test_adv.append(attack(i, label))
TypeError: __call__() missing 1 required positional argument: 'criterion'

Does anyone know if the BrendelBethgeAttack has been correctly implemented yet? I seem to be running into problems only with this attack.

**Comment by mcguires5** [comment] 2020-04-20 21:53
I have noticed the new syntax in the new foolbox update and corrected the code, but the attack is still failing with the message
```
  File "C:/Users/Sean/PycharmProjects/BroadSpectrumDefense/attacks_ART.py", line 411, in generate_attack_Foolbox
    adv_ex, _, success = attack(fmodel, img, label, epsilons=None)
  File "C:\Users\Sean\AppData\Local\Programs\Python\Python37\lib\site-packages\foolbox\attacks\base.py", line 410, in __call__
    xp = self.run(model, x, criterion, early_stop=early_stop, **kwargs)
  File "C:\Users\Sean\AppData\Local\Programs\Python\Python37\lib\site-packages\foolbox\attacks\brendel_bethge.py", line 430, in run
    starting_points = self.init_attack.run(model, originals, criterion_)
AttributeError: 'NoneType' object has no attribute 'run'
```

**Comment by divyam3897** [comment] 2020-04-21 09:27
This can be fixed by changing that line to `init_attack.run` as in the code `self.init_attack` is still None.

**Comment by wielandbrendel** [comment] 2020-06-18 20:54
@divyam3897 @mcguires5 Do you have a minimum working prototype for testing? I cannot reproduce the issue you are seeing.

**Comment by wielandbrendel** [comment] 2020-06-18 21:12
Please also see the minimum example in https://github.com/wielandbrendel/brendel_bethge_attack

**Closed** 2020-07-21 20:48 UTC

**Comment by mcguires5** [comment] 2020-07-21 20:49
In Foolbox 3 the syntax of calling the attack was changed to 
```attack = foolbox.attacks.L2BrendelBethgeAttack()
epsilons = [0.0006, 0.0015, 0.03, 0.1, 0.15, 0.33, 0.5]
adv_ex, adv, success = attack(fmodel, img, label, epsilons=epsilons)```
